In [1]:
import torch

In [2]:
batch = 4
dim = 32
length = 8

In [4]:
x = torch.randn(batch, length, dim)

In [5]:
x[0].shape

torch.Size([8, 32])

In [6]:
x[0][0]

tensor([-0.3218, -0.5934, -0.6457, -0.0343,  0.5731,  0.3519, -1.1540, -1.3216,
         2.4002, -1.4375, -0.5027, -0.8860,  0.0802, -0.1840, -0.1510,  1.1869,
        -1.4584, -0.4037, -1.2319,  0.5641, -1.6608, -1.2226,  3.0345, -2.1091,
         0.7974,  0.9672,  0.6409, -0.0627,  0.9411,  1.2646, -2.6790,  1.4418])

In [7]:
tril = torch.tril(torch.ones(length, length))

In [8]:
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
weights = torch.zeros(length, length)
weights

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
weights = weights.masked_fill(tril == 0, float('-inf'))
weights

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
import torch.nn.functional as F

In [13]:
weights = F.softmax(weights, dim=1)

In [14]:
weights

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [15]:
out = weights @ x
out

tensor([[[-3.2176e-01, -5.9335e-01, -6.4569e-01,  ...,  1.2646e+00,
          -2.6790e+00,  1.4418e+00],
         [ 4.6762e-01, -1.5307e+00, -8.5448e-01,  ...,  9.9466e-01,
          -9.4385e-01,  6.2644e-01],
         [ 7.7849e-01, -1.2798e+00, -6.4685e-01,  ...,  8.6453e-01,
          -7.1234e-01,  4.2838e-01],
         ...,
         [ 5.2829e-01, -1.8593e-01, -3.2306e-01,  ...,  2.6652e-01,
          -6.8820e-01, -1.2212e-01],
         [ 4.9278e-01, -4.8894e-01, -3.5553e-01,  ...,  2.6846e-01,
          -3.8853e-01,  2.2900e-03],
         [ 4.3375e-01, -3.9843e-01, -3.4014e-01,  ...,  1.2466e-01,
          -4.1833e-01,  1.0254e-01]],

        [[-7.9317e-01, -2.1461e-01, -2.3176e+00,  ...,  7.5114e-02,
          -3.2110e-01,  1.4645e-01],
         [-2.8730e-01,  5.8756e-02, -9.4267e-01,  ..., -7.4751e-02,
           8.1403e-03, -3.5283e-01],
         [ 1.6992e-01,  3.2591e-02, -7.4388e-01,  ...,  5.6302e-03,
          -1.7350e-01,  4.3518e-01],
         ...,
         [-4.8394e-01, -6