In [2]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
# criterion = nn.XXLoss()
# model = XXNet()
# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
#
# for _ in range(epochs):
#     for images, labels in data_loader:
#         output = model(images)
#         loss = criterion(output, labels)
#
#         # model.parameters() 连接layer与layer之前的weights, bias
#         # model.parameters().grad = 0
#         optimizer.zero_grad()
#
#         # required_grad = True
#         loss.backward()
#
#         # model.parameters(): 连接layer与layer之前的weights, bias
#         # model.parameters() += lr * model.parameters().grad
#         optimizer.step()

In [7]:
x = torch.tensor([1., 2.], requires_grad=True)
y = 100 * x
loss = y.sum()
optimizer = torch.optim.SGD([x], lr=0.001)

In [8]:
optimizer

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [9]:
optimizer.__dir__()

['defaults',
 '_optimizer_step_pre_hooks',
 '_optimizer_step_post_hooks',
 '_zero_grad_profile_name',
 'state',
 'param_groups',
 '_warned_capturable_if_run_uncaptured',
 '__module__',
 '__init__',
 '__setstate__',
 '_init_group',
 'step',
 '__doc__',
 '__getstate__',
 '__repr__',
 '_cuda_graph_capture_health_check',
 '_optimizer_step_code',
 'profile_hook_step',
 '_patch_step_function',
 'register_step_pre_hook',
 'register_step_post_hook',
 'state_dict',
 'load_state_dict',
 'zero_grad',
 'add_param_group',
 '__dict__',
 '__weakref__',
 '__new__',
 '__hash__',
 '__str__',
 '__getattribute__',
 '__setattr__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__reduce_ex__',
 '__reduce__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [10]:
x.grad

In [11]:
x.data

tensor([1., 2.])

In [12]:
optimizer.zero_grad()

In [13]:
loss.backward()

In [14]:
x.grad

tensor([100., 100.])

In [15]:
x.data

tensor([1., 2.])

In [16]:
optimizer.step()

In [17]:
x.grad

tensor([100., 100.])

In [18]:
x.data

tensor([0.9000, 1.9000])