In [1]:
import torch
from torch import nn

#### BCELoss 计算过程
- input
    - 未经过sigmoid的network的输出（一个样本对应一维的输出）
- 计算过程 & output
    - step1：计算 sigmoid，将 1d 的 logits 转换为 p(class=1|x) 的概率
    - step2: 计算 l1 = -(y_i * log(y_hat_i) + (1-y_i) * log(1-y_hat_i))
    - step3: 计算均值 l = mean(l1)

In [4]:
m = nn.Sigmoid()
loss = nn.BCELoss()
inputs = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)
output = loss(m(inputs), target)

In [5]:
print(inputs, target)

tensor([0.6407, 0.5692, 0.3490], requires_grad=True) tensor([1., 1., 1.])


In [6]:
m(inputs)

tensor([0.6549, 0.6386, 0.5864], grad_fn=<SigmoidBackward0>)

In [7]:
1/(1+torch.exp(-inputs))

tensor([0.6549, 0.6386, 0.5864], grad_fn=<MulBackward0>)

In [8]:
output

tensor(0.4685, grad_fn=<BinaryCrossEntropyBackward0>)

In [9]:
-(target * torch.log(m(inputs)) + (1-target)*torch.log(1-m(inputs)))

tensor([0.4233, 0.4485, 0.5338], grad_fn=<NegBackward0>)

In [10]:
torch.mean(-(target * torch.log(m(inputs)) + (1-target)*torch.log(1-m(inputs))))

tensor(0.4685, grad_fn=<MeanBackward0>)

In [11]:
output.backward()

In [12]:
inputs.grad

tensor([-0.1150, -0.1205, -0.1379])

In [13]:
-(target - m(inputs))/3

tensor([-0.1150, -0.1205, -0.1379], grad_fn=<DivBackward0>)

In [14]:
loss = nn.BCEWithLogitsLoss()
loss(inputs, target)

tensor(0.4685, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)