In [1]:
import numpy as np
import torch
from torch import nn

In [2]:
x = torch.tensor(1, dtype=torch.float, requires_grad=True)
x

tensor(1., requires_grad=True)

In [3]:
x.grad

In [4]:
y = x.sigmoid()

In [5]:
y

tensor(0.7311, grad_fn=<SigmoidBackward0>)

In [6]:
1/(1+np.exp(-1))

0.7310585786300049

In [7]:
y.backward()

In [8]:
x.grad

tensor(0.1966)

In [9]:
x.sigmoid() * (1 - x.sigmoid())

tensor(0.1966, grad_fn=<MulBackward0>)

In [10]:
sigmoid = nn.Sigmoid()
sigmoid(x) * (1 - sigmoid(x))

tensor(0.1966, grad_fn=<MulBackward0>)

In [11]:
x = torch.tensor([1, 2, 3], dtype=torch.float, requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [13]:
y = x.sigmoid().sum()
y

tensor(2.5644, grad_fn=<SumBackward0>)

In [14]:
x.grad

In [15]:
y.backward()

In [16]:
x.grad

tensor([0.1966, 0.1050, 0.0452])

In [18]:
x.sigmoid() * (1 - x.sigmoid())

tensor([0.1966, 0.1050, 0.0452], grad_fn=<MulBackward0>)

In [21]:
x = torch.tensor(2, dtype=torch.float, requires_grad=True)
y = sigmoid(x) ** 2
y

tensor(0.7758, grad_fn=<PowBackward0>)

In [22]:
x.grad

In [23]:
y.backward()

In [24]:
x.grad

tensor(0.1850)