In [1]:
import torch

In [2]:
logits = torch.tensor([1.1, 2.2, 0.2, -1.7])
print(logits.softmax(dim=0))
print(torch.nn.Softmax(dim=0)(logits))

tensor([0.2236, 0.6718, 0.0909, 0.0136])
tensor([0.2236, 0.6718, 0.0909, 0.0136])


In [3]:
z = torch.tensor([1.1, 2.2, .2, -1.7], requires_grad=True)
s = z.softmax(dim=0)

In [4]:
s

tensor([0.2236, 0.6718, 0.0909, 0.0136], grad_fn=<SoftmaxBackward0>)

In [5]:
s[0].backward()

In [6]:
z.grad

tensor([ 0.1736, -0.1502, -0.0203, -0.0030])

In [7]:
s[1].backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [8]:
z = torch.tensor([1.1, 2.2, .2, -1.7], requires_grad=True)
s = z.softmax(dim=0)
s[1].backward()
z.grad

tensor([-0.1502,  0.2205, -0.0611, -0.0091])

In [9]:
from torch.autograd.functional import jacobian
def softmax(z1, z2, z3, z4):
    exp_z = [torch.exp(z1), torch.exp(z2), torch.exp(z3), torch.exp(z4)]
    return tuple([e/sum(exp_z) for e in exp_z])
z1, z2, z3, z4 = [torch.tensor(1.1), torch.tensor(2.2), torch.tensor(.2), torch.tensor(-1.7)]
jacobian(softmax,(z1,z2,z3, z4))

((tensor(0.1736), tensor(-0.1502), tensor(-0.0203), tensor(-0.0030)),
 (tensor(-0.1502), tensor(0.2205), tensor(-0.0611), tensor(-0.0091)),
 (tensor(-0.0203), tensor(-0.0611), tensor(0.0827), tensor(-0.0012)),
 (tensor(-0.0030), tensor(-0.0091), tensor(-0.0012), tensor(0.0134)))