In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
# Data Generation
true_b = 1
true_w = 2
N = 100

np.random.seed(42)
x = np.random.rand(N, 1)
epsilon = (.1 * np.random.randn(N, 1))
y = true_b + true_w * x + epsilon

In [3]:
idx = np.arange(N)
np.random.shuffle(idx)

train_idx = idx[:int(N * .8)]
val_idx = idx[int(N * .8):]

x_train, y_train = x[train_idx], y[train_idx]
x_val, y_val = x[val_idx], y[val_idx]

In [4]:
b = np.random.randn(1)
w = np.random.randn(1)

w, b

(array([0.18645431]), array([-2.02514259]))

In [5]:
yhat = b + w * x_train

In [7]:
loss = np.mean((yhat - y_train) ** 2)
loss

15.444680120636235

In [8]:
b_range = np.linspace(true_b - 3, true_b + 3, 101)
w_range = np.linspace(true_w - 3, true_w + 3, 101)

bs, ws = np.meshgrid(b_range, w_range)
bs.shape, ws.shape

((101, 101), (101, 101))

In [10]:
b_range, w_range

(array([-2.  , -1.94, -1.88, -1.82, -1.76, -1.7 , -1.64, -1.58, -1.52,
        -1.46, -1.4 , -1.34, -1.28, -1.22, -1.16, -1.1 , -1.04, -0.98,
        -0.92, -0.86, -0.8 , -0.74, -0.68, -0.62, -0.56, -0.5 , -0.44,
        -0.38, -0.32, -0.26, -0.2 , -0.14, -0.08, -0.02,  0.04,  0.1 ,
         0.16,  0.22,  0.28,  0.34,  0.4 ,  0.46,  0.52,  0.58,  0.64,
         0.7 ,  0.76,  0.82,  0.88,  0.94,  1.  ,  1.06,  1.12,  1.18,
         1.24,  1.3 ,  1.36,  1.42,  1.48,  1.54,  1.6 ,  1.66,  1.72,
         1.78,  1.84,  1.9 ,  1.96,  2.02,  2.08,  2.14,  2.2 ,  2.26,
         2.32,  2.38,  2.44,  2.5 ,  2.56,  2.62,  2.68,  2.74,  2.8 ,
         2.86,  2.92,  2.98,  3.04,  3.1 ,  3.16,  3.22,  3.28,  3.34,
         3.4 ,  3.46,  3.52,  3.58,  3.64,  3.7 ,  3.76,  3.82,  3.88,
         3.94,  4.  ]),
 array([-1.  , -0.94, -0.88, -0.82, -0.76, -0.7 , -0.64, -0.58, -0.52,
        -0.46, -0.4 , -0.34, -0.28, -0.22, -0.16, -0.1 , -0.04,  0.02,
         0.08,  0.14,  0.2 ,  0.26,  0.32,  0.38,  0.

In [19]:
error = yhat - y_train
loss = (error ** 2).mean()
loss

15.444680120636235

In [22]:
x_train.shape

(80, 1)

In [23]:
x_train[0]

array([0.77127035])

In [24]:
dummy_x = x_train[0]
dummy_hat = bs + ws * dummy_x
dummy_hat.shape

(101, 101)

In [25]:
all_predictions = np.apply_along_axis(
    func1d=lambda x: bs + ws * x,
    axis=1,
    arr=x_train
)
all_predictions.shape

(80, 101, 101)

In [28]:
x_train.shape, bs.shape, ws.shape

((80, 1), (101, 101), (101, 101))

In [30]:
x_train[0] * ws + bs

array([[-2.77127035, -2.71127035, -2.65127035, ...,  3.10872965,
         3.16872965,  3.22872965],
       [-2.72499413, -2.66499413, -2.60499413, ...,  3.15500587,
         3.21500587,  3.27500587],
       [-2.67871791, -2.61871791, -2.55871791, ...,  3.20128209,
         3.26128209,  3.32128209],
       ...,
       [ 1.76379929,  1.82379929,  1.88379929, ...,  7.64379929,
         7.70379929,  7.76379929],
       [ 1.81007551,  1.87007551,  1.93007551, ...,  7.69007551,
         7.75007551,  7.81007551],
       [ 1.85635173,  1.91635173,  1.97635173, ...,  7.73635173,
         7.79635173,  7.85635173]])

In [32]:
ws, bs

(array([[-1.  , -1.  , -1.  , ..., -1.  , -1.  , -1.  ],
        [-0.94, -0.94, -0.94, ..., -0.94, -0.94, -0.94],
        [-0.88, -0.88, -0.88, ..., -0.88, -0.88, -0.88],
        ...,
        [ 4.88,  4.88,  4.88, ...,  4.88,  4.88,  4.88],
        [ 4.94,  4.94,  4.94, ...,  4.94,  4.94,  4.94],
        [ 5.  ,  5.  ,  5.  , ...,  5.  ,  5.  ,  5.  ]]),
 array([[-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
        [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
        [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
        ...,
        [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
        [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ],
        [-2.  , -1.94, -1.88, ...,  3.88,  3.94,  4.  ]]))