In [1]:
import torch

### 基本介绍

- 复杂的接口：一些抽象的接口的深入理解
    - 理解复杂的代码
    - 有助于构建复杂的神经网络，且清晰，不出错。
- 基于index在原始tensor上选择
    - 行选多个，提供的列值（dim=1）
        - 多个时，每个行选的必须保持一直
    - 列选多个（列选1个是一种特例），提供的是行值（dim=0）
- 要求
    - input tensor与index的dim相同
    - input.shape < input.shape
- 应用场景
    - batch sample多分类问题的分类输出，获得各个true label上的score(logits)/probs （行选1个）
        - batch sample: n*c
        - index(true label): n*1

In [2]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[1, 0], [0, 1]]))

tensor([[2, 1],
        [3, 4]])

In [3]:
t = torch.arange(1, 10).view(3, 3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
t.gather(1, torch.tensor([[0, 2], [1, 2]]))

tensor([[1, 3],
        [5, 6]])

如果是想选择(1, 4), (2, 8)，提供的行值是（0， 0）（1， 2）

In [5]:
t.gather(0, torch.tensor(((0, 0), (1, 2))))

tensor([[1, 2],
        [4, 8]])